package com.airiea.dao.orm;

import com.airiea.model.enums.Model;
import com.airiea.model.enums.ModelObject;
import com.airiea.model.enums.ModelOwner;
import com.airiea.model.enums.UpdateType;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "agent-configs")
public class AgentConfig {
    private static final Double DEFAULT_TEMPERATURE = 0.2;
    private static final Boolean DEFAULT_STREAM = false;
    private static final String NULL_KNOWLEDGE_CONTENT = "NULL";
    private static final Integer DEFAULT_MAX_TOKEN = 2048;

    @JsonProperty("agent_name")
    @DynamoDBHashKey(attributeName = "agent_name")
    String agentName;

    /**
     * Describe the background of the task executor
     */
    @DynamoDBAttribute(attributeName = "agent_role")
    @JsonProperty("agent_role")
    String agentRole;

    @DynamoDBAttribute(attributeName = "agent_goal")
    @JsonProperty("agent_goal")
    String agentGoal;

    @DynamoDBAttribute(attributeName = "ability_name")
    @JsonProperty("ability_name")
    String abilityName;

    @JsonProperty("created_date")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBAttribute(attributeName = "created_date")
    Date createdDate;

    @JsonProperty("updated_date")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBAttribute(attributeName = "updated_date")
    Date updatedDate;
}

