package com.airiea.dao.orm;

import com.airiea.model.enums.ErrorCode;
import com.airiea.model.enums.Status;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "task-records")
public class TaskRecord {
    @DynamoDBHashKey(attributeName = "task_id")
    @JsonProperty("task_id")
    String taskId;

    @DynamoDBAttribute(attributeName = "knowledge_id")
    @JsonProperty("knowledge_id")
    String knowledgeId;

    @DynamoDBIndexHashKey(attributeName = "entity_id", globalSecondaryIndexName = "entity_id-agent_name")
    @DynamoDBAttribute(attributeName = "entity_id")
    @JsonProperty("entity_id")
    String entityId;

    @DynamoDBIndexRangeKey(attributeName = "agent_name", globalSecondaryIndexName = "entity_id-agent_name")
    @DynamoDBAttribute(attributeName = "agent_name")
    @JsonProperty("agent_name")
    String agentName;

    @DynamoDBAttribute(attributeName = "task_count")
    @JsonProperty("task_count")
    Integer taskCount;

    @DynamoDBAttribute(attributeName = "text_input")
    @JsonProperty("text_input")
    String textInput;

    @DynamoDBAttribute(attributeName = "text_output")
    @JsonProperty("text_output")
    String textOutput;

    @DynamoDBAttribute(attributeName = "embedding_input")
    @JsonProperty("embedding_input")
    List<Double> embeddingInput;

    @DynamoDBAttribute(attributeName = "embedding_output")
    @JsonProperty("embedding_output")
    List<Double> embeddingOutput;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "status")
    Status status;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "error_code")
    @JsonProperty("error_code")
    ErrorCode errorCode;

    @DynamoDBAttribute(attributeName = "error_message")
    @JsonProperty("error_message")
    String errorMessage;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBAttribute(attributeName = "created_date")
    @JsonProperty("created_date")
    Date createdDate;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBAttribute(attributeName = "updated_date")
    @JsonProperty("updated_date")
    Date updatedDate;
}
